version: "3.7"
services:
  db:
    image: postgres:15
    container_name: mobile_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  app:
    image: app_image
    build:
      context: .
    container_name: mobile_app
    env_file:
      - .env-non-dev
    ports:
      - 8888:8000
    depends_on:
      - db
    command: ["./docker/app.sh"]
